"""Add vehicle registration requests table

Revision ID: 17ad8d3b052c
Revises: a036c4687655
Create Date: 2025-09-21 16:51:31.287361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ad8d3b052c'
down_revision = 'a036c4687655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_service_booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_make', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=50), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('current_mileage', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('service_category', sa.String(length=50), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.String(length=10), nullable=False),
    sa.Column('service_location', sa.String(length=100), nullable=False),
    sa.Column('service_specifications', sa.JSON(), nullable=True),
    sa.Column('additional_services', sa.JSON(), nullable=True),
    sa.Column('customer_complaints', sa.Text(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_center', sa.String(length=100), nullable=True),
    sa.Column('assigned_mechanic', sa.String(length=100), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('confirmation_sent', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_service_booking_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_service_booking_requests_request_number'), ['request_number'], unique=True)

    op.create_table('vehicle_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('registration_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('vehicle_color', sa.String(length=50), nullable=False),
    sa.Column('engine_number', sa.String(length=100), nullable=True),
    sa.Column('chassis_number', sa.String(length=100), nullable=True),
    sa.Column('current_registration_number', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_address', sa.Text(), nullable=False),
    sa.Column('owner_phone', sa.String(length=20), nullable=False),
    sa.Column('owner_email', sa.String(length=120), nullable=True),
    sa.Column('owner_state', sa.String(length=50), nullable=False),
    sa.Column('owner_lga', sa.String(length=100), nullable=False),
    sa.Column('vehicle_purpose', sa.String(length=50), nullable=False),
    sa.Column('purchase_receipt', sa.Boolean(), nullable=True),
    sa.Column('customs_papers', sa.Boolean(), nullable=True),
    sa.Column('insurance_certificate', sa.Boolean(), nullable=True),
    sa.Column('roadworthiness_certificate', sa.Boolean(), nullable=True),
    sa.Column('driver_license', sa.Boolean(), nullable=True),
    sa.Column('service_center', sa.String(length=100), nullable=True),
    sa.Column('processing_priority', sa.String(length=20), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('pickup_required', sa.Boolean(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('progress_notes', sa.JSON(), nullable=True),
    sa.Column('documents_verified_at', sa.DateTime(), nullable=True),
    sa.Column('frsc_approved_at', sa.DateTime(), nullable=True),
    sa.Column('plate_produced_at', sa.DateTime(), nullable=True),
    sa.Column('ready_for_pickup_at', sa.DateTime(), nullable=True),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('government_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('new_registration_number', sa.String(length=20), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('uploaded_documents', sa.JSON(), nullable=True),
    sa.Column('generated_documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_registration_requests')
    with op.batch_alter_table('car_service_booking_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_service_booking_requests_request_number'))

    op.drop_table('car_service_booking_requests')
    # ### end Alembic commands ###
