"""Add logistics quote request table

Revision ID: 7c4151c3f8ab
Revises: 9af2432f3829
Create Date: 2025-09-19 20:48:31.326831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4151c3f8ab'
down_revision = '9af2432f3829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_city', sa.String(length=100), nullable=False),
    sa.Column('pickup_state', sa.String(length=100), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('pickup_time', sa.String(length=20), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_city', sa.String(length=100), nullable=False),
    sa.Column('delivery_state', sa.String(length=100), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_time', sa.String(length=20), nullable=True),
    sa.Column('package_description', sa.Text(), nullable=False),
    sa.Column('package_weight', sa.Float(), nullable=True),
    sa.Column('package_dimensions', sa.JSON(), nullable=True),
    sa.Column('package_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('freight_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('urgency_level', sa.String(length=30), nullable=True),
    sa.Column('supply_chain_type', sa.String(length=50), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('volume_per_month', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('quote_valid_until', sa.Date(), nullable=True),
    sa.Column('quote_notes', sa.Text(), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logistics_quote_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_quote_requests_quote_number'), ['quote_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistics_quote_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_quote_requests_quote_number'))

    op.drop_table('logistics_quote_requests')
    # ### end Alembic commands ###
