"""Add gadgets and accessories models

Revision ID: 81b7dc92ff39
Revises: 869f94886232
Create Date: 2025-09-19 20:24:26.495919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b7dc92ff39'
down_revision = '869f94886232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('accessory_type', sa.String(length=50), nullable=True),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('compatible_devices', sa.JSON(), nullable=True),
    sa.Column('compatibility_type', sa.String(length=50), nullable=True),
    sa.Column('device_categories', sa.JSON(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('durability_rating', sa.String(length=20), nullable=True),
    sa.Column('color_options', sa.JSON(), nullable=True),
    sa.Column('special_features', sa.JSON(), nullable=True),
    sa.Column('battery_capacity', sa.String(length=20), nullable=True),
    sa.Column('charging_speed', sa.String(length=50), nullable=True),
    sa.Column('wireless_charging', sa.Boolean(), nullable=True),
    sa.Column('audio_features', sa.JSON(), nullable=True),
    sa.Column('driver_size', sa.String(length=20), nullable=True),
    sa.Column('frequency_response', sa.String(length=50), nullable=True),
    sa.Column('impedance', sa.String(length=20), nullable=True),
    sa.Column('connectivity_type', sa.JSON(), nullable=True),
    sa.Column('wireless_range', sa.String(length=20), nullable=True),
    sa.Column('protection_level', sa.String(length=50), nullable=True),
    sa.Column('screen_protection', sa.Boolean(), nullable=True),
    sa.Column('waterproof', sa.Boolean(), nullable=True),
    sa.Column('smart_features', sa.JSON(), nullable=True),
    sa.Column('app_compatibility', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('processor_brand', sa.String(length=50), nullable=True),
    sa.Column('processor_model', sa.String(length=100), nullable=True),
    sa.Column('processor_generation', sa.String(length=20), nullable=True),
    sa.Column('cores', sa.String(length=20), nullable=True),
    sa.Column('base_clock', sa.String(length=20), nullable=True),
    sa.Column('boost_clock', sa.String(length=20), nullable=True),
    sa.Column('ram_size', sa.String(length=20), nullable=True),
    sa.Column('ram_type', sa.String(length=20), nullable=True),
    sa.Column('ram_speed', sa.String(length=20), nullable=True),
    sa.Column('max_ram_capacity', sa.String(length=20), nullable=True),
    sa.Column('storage_type', sa.String(length=50), nullable=True),
    sa.Column('storage_capacity', sa.String(length=50), nullable=True),
    sa.Column('additional_storage_slots', sa.Boolean(), nullable=True),
    sa.Column('graphics_type', sa.String(length=20), nullable=True),
    sa.Column('graphics_card', sa.String(length=100), nullable=True),
    sa.Column('graphics_memory', sa.String(length=20), nullable=True),
    sa.Column('screen_size', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('display_type', sa.String(length=50), nullable=True),
    sa.Column('refresh_rate', sa.String(length=20), nullable=True),
    sa.Column('color_gamut', sa.String(length=50), nullable=True),
    sa.Column('touchscreen', sa.Boolean(), nullable=True),
    sa.Column('operating_system', sa.String(length=50), nullable=True),
    sa.Column('os_edition', sa.String(length=50), nullable=True),
    sa.Column('pre_installed_software', sa.JSON(), nullable=True),
    sa.Column('wifi_standard', sa.String(length=20), nullable=True),
    sa.Column('bluetooth_version', sa.String(length=20), nullable=True),
    sa.Column('ethernet_port', sa.Boolean(), nullable=True),
    sa.Column('usb_ports', sa.JSON(), nullable=True),
    sa.Column('hdmi_ports', sa.Integer(), nullable=True),
    sa.Column('audio_jack', sa.Boolean(), nullable=True),
    sa.Column('sd_card_slot', sa.Boolean(), nullable=True),
    sa.Column('battery_capacity', sa.String(length=20), nullable=True),
    sa.Column('battery_life', sa.String(length=50), nullable=True),
    sa.Column('power_adapter', sa.String(length=50), nullable=True),
    sa.Column('keyboard_type', sa.String(length=50), nullable=True),
    sa.Column('trackpad_features', sa.JSON(), nullable=True),
    sa.Column('biometric_features', sa.JSON(), nullable=True),
    sa.Column('webcam_resolution', sa.String(length=20), nullable=True),
    sa.Column('primary_use_case', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('technical_support_included', sa.Boolean(), nullable=True),
    sa.Column('support_duration', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smartphones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('operating_system', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('storage_options', sa.JSON(), nullable=True),
    sa.Column('ram', sa.String(length=20), nullable=True),
    sa.Column('expandable_storage', sa.Boolean(), nullable=True),
    sa.Column('max_storage_expansion', sa.String(length=20), nullable=True),
    sa.Column('rear_camera', sa.String(length=100), nullable=True),
    sa.Column('front_camera', sa.String(length=50), nullable=True),
    sa.Column('camera_features', sa.JSON(), nullable=True),
    sa.Column('battery_capacity', sa.String(length=20), nullable=True),
    sa.Column('fast_charging', sa.String(length=50), nullable=True),
    sa.Column('wireless_charging', sa.Boolean(), nullable=True),
    sa.Column('processor', sa.String(length=100), nullable=True),
    sa.Column('screen_size', sa.String(length=20), nullable=True),
    sa.Column('display_type', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('refresh_rate', sa.String(length=20), nullable=True),
    sa.Column('network_support', sa.JSON(), nullable=True),
    sa.Column('dual_sim', sa.Boolean(), nullable=True),
    sa.Column('bluetooth_version', sa.String(length=20), nullable=True),
    sa.Column('wifi_standards', sa.JSON(), nullable=True),
    sa.Column('water_resistance', sa.String(length=20), nullable=True),
    sa.Column('biometric_features', sa.JSON(), nullable=True),
    sa.Column('build_material', sa.String(length=100), nullable=True),
    sa.Column('warranty_status', sa.String(length=20), nullable=True),
    sa.Column('included_accessories', sa.JSON(), nullable=True),
    sa.Column('trade_in_eligible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smartphones')
    op.drop_table('product_images')
    op.drop_table('laptops')
    op.drop_table('accessories')
    # ### end Alembic commands ###
