"""Add enhanced loan system tables

Revision ID: 869f94886232
Revises: 
Create Date: 2025-09-19 19:54:12.397686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '869f94886232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enhanced_loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('account_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('bvn', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('alternate_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('residential_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('state_of_origin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lga', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('next_of_kin_relationship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('employer_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('employer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('other_income_source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_registration_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('years_in_business', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_monthly_revenue', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('collateral_location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('policy_agreed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('terms_agreed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('data_processing_agreed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('identity_document', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('income_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('employment_letter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bank_statement', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('collateral_documents', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('business_documents', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('additional_documents', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.drop_column('documents')

    with op.batch_alter_table('loan_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_collateral', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requires_employment_proof', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_debt_to_income_ratio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_types', schema=None) as batch_op:
        batch_op.drop_column('max_debt_to_income_ratio')
        batch_op.drop_column('requires_employment_proof')
        batch_op.drop_column('requires_collateral')

    with op.batch_alter_table('enhanced_loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('employment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('additional_documents')
        batch_op.drop_column('business_documents')
        batch_op.drop_column('collateral_documents')
        batch_op.drop_column('bank_statement')
        batch_op.drop_column('employment_letter')
        batch_op.drop_column('income_proof')
        batch_op.drop_column('identity_document')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('data_processing_agreed')
        batch_op.drop_column('terms_agreed')
        batch_op.drop_column('policy_agreed')
        batch_op.drop_column('collateral_location')
        batch_op.drop_column('average_monthly_revenue')
        batch_op.drop_column('years_in_business')
        batch_op.drop_column('business_type')
        batch_op.drop_column('business_registration_number')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_name')
        batch_op.drop_column('other_income_source')
        batch_op.drop_column('job_title')
        batch_op.drop_column('employer_phone')
        batch_op.drop_column('employer_address')
        batch_op.drop_column('next_of_kin_relationship')
        batch_op.drop_column('next_of_kin_phone')
        batch_op.drop_column('next_of_kin_name')
        batch_op.drop_column('lga')
        batch_op.drop_column('state_of_origin')
        batch_op.drop_column('residential_address')
        batch_op.drop_column('alternate_phone')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('bvn')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')

    op.drop_table('loan_policies')
    # ### end Alembic commands ###
