"""Add hotel service request model

Revision ID: 9af2432f3829
Revises: 81b7dc92ff39
Create Date: 2025-09-19 20:34:28.936908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af2432f3829'
down_revision = '81b7dc92ff39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_email', sa.String(length=120), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('hotel_name', sa.String(length=200), nullable=True),
    sa.Column('hotel_location', sa.String(length=200), nullable=True),
    sa.Column('hotel_size', sa.String(length=100), nullable=True),
    sa.Column('current_management_system', sa.String(length=200), nullable=True),
    sa.Column('specific_requirements', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('number_of_staff', sa.Integer(), nullable=True),
    sa.Column('training_areas', sa.JSON(), nullable=True),
    sa.Column('current_skill_level', sa.String(length=50), nullable=True),
    sa.Column('current_booking_system', sa.String(length=200), nullable=True),
    sa.Column('integration_requirements', sa.Text(), nullable=True),
    sa.Column('expected_monthly_bookings', sa.Integer(), nullable=True),
    sa.Column('current_operations_challenges', sa.Text(), nullable=True),
    sa.Column('departments_to_manage', sa.JSON(), nullable=True),
    sa.Column('quality_standards_required', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('consultation_scheduled', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quote_provided', sa.Boolean(), nullable=True),
    sa.Column('quote_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hotel_service_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_service_requests_request_number'), ['request_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_service_requests_request_number'))

    op.drop_table('hotel_service_requests')
    # ### end Alembic commands ###
