"""Add rental booking request table

Revision ID: a036c4687655
Revises: 7c4151c3f8ab
Create Date: 2025-09-20 09:35:04.614217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a036c4687655'
down_revision = '7c4151c3f8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('rental_type', sa.String(length=50), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('preferred_specifications', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rental_duration_days', sa.Integer(), nullable=False),
    sa.Column('flexible_dates', sa.Boolean(), nullable=True),
    sa.Column('pickup_location', sa.Text(), nullable=True),
    sa.Column('delivery_required', sa.Boolean(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('driver_required', sa.Boolean(), nullable=True),
    sa.Column('installation_required', sa.Boolean(), nullable=True),
    sa.Column('setup_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('budget_range_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_range_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('usage_purpose', sa.String(length=200), nullable=True),
    sa.Column('number_of_users', sa.Integer(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('quoted_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quote_breakdown', sa.JSON(), nullable=True),
    sa.Column('quote_notes', sa.Text(), nullable=True),
    sa.Column('quote_valid_until', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(length=10), nullable=True),
    sa.Column('rental_booking_id', sa.Integer(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rental_booking_id'], ['rental_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_booking_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_booking_requests_request_number'), ['request_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_booking_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_booking_requests_request_number'))

    op.drop_table('rental_booking_requests')
    # ### end Alembic commands ###
